# Generated by Django 6.0.2 on 2026-02-05 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
    ]
