# Generated by Django 6.0.2 on 2026-02-05 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(help_text='ex. Dog walking, Home sitting, Overnight care, etc.', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
