# Generated by Django 6.0.2 on 2026-02-05 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_slug_alter_service_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ex. Dog, Cat, Rabbit, etc.', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
        ),
    ]
