# Generated by Django 6.0.2 on 2026-02-05 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_pettype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
    ]
