# Generated by Django 6.0.2 on 2026-02-05 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caretakers', '0001_initial'),
        ('services', '0005_pettype'),
    ]

    operations = [
        migrations.CreateModel(
            name='HireRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=80)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='new', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caretaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hire_requests', to='caretakers.caretaker')),
                ('pet_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hire_requests', to='services.pettype')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hire_requests', to='services.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
