# Generated by Django 6.0.2 on 2026-02-23 00:40

import requests.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hirerequest',
            name='start_date',
            field=models.DateField(validators=[requests.validators.start_date_not_past]),
        ),
    ]
