# Generated by Django 6.0.2 on 2026-02-05 22:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0005_pettype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caretaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='caretakers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet_types', models.ManyToManyField(blank=True, related_name='caretakers', to='services.pettype')),
                ('services', models.ManyToManyField(blank=True, related_name='caretakers', to='services.service')),
            ],
            options={
                'ordering': ['name', 'city'],
            },
        ),
    ]
