# Generated by Django 6.0.2 on 2026-07-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caretakers', '0002_caretaker_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretaker',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
