# Generated by Django 6.0.2 on 2026-07-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caretakers', '0003_caretaker_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretaker',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
